#!/bin/bash

file=$1
size=$(stat --printf="%s" "$file")
size=$((size/1024))

#T_OPT="-C -R -D -k tg-server.pub --disable-link-preview"
#(echo "channel_list"; sleep 1; echo "msg Home \"[ Incomming file ]\""; echo "send_file Home $file"; echo "safe_quit") | /usr/local/bin/telegram-cli $T_OPT

# TOKEN=bot toekn API key
# CHAT_ID=Identifier
source /home/nico/.config/telegram/credentials
URL="https://api.telegram.org/bot$TOKEN"

sendTelegram() {
        curl -s \
        -X POST \
        "$URL/sendMessage" \
        --data-urlencode text="$MESSAGE" \
        -d parse_mode=Markdown \
        -d chat_id=$CHAT_ID \
        -o /dev/null
}

sendTelegramFile() {
        curl -s \
        -F document=@"$1" "$URL/sendDocument" \
        -F chat_id=$CHAT_ID \
        -o /dev/null
}

MESSAGE=$(echo -e "*[ Incomming file ]*\n_Uploading $size KB..._")
sendTelegram
sendTelegramFile $file